### ISSUE TITLE
GalaxySpace seems to alter some physics in Enviromine

### ISSUE THREAD

**Issue by lllMohandarlll** [BlesseNtumble/GalaxySpace#110]
Hello, good job for this great addon!
By the way, I found a weird behavior when using it togheter with Enviromine.
Normally with enviromine installed when you break a log block from a tree it fall down cause of physics.
Adding galacticraft seems doesn't affect this property, but adding galaxy space when you finally go to cut your tree log down it divide the physics for each block.
What I mean is;
if in the beginning when you break the bottom wood-log block of the tree the entire tree woul have fall down, actually the behavior is: when you break the bottom block, only the above wood block fall down, and the rest of the tree remain unaffected to enviromine physics.

http://i.imgur.com/xrUqta1.png

Have you any idea what would cause this behavior?

**Comment by lllMohandarlll** [comment]
btw, sorry if I'm asking, I've noticed you've labeled this as "pending verification", is that expected from my side or from your side?
you can easy check this in a clean istance with enviromine + galaxyspace (&galacticraft) installed

**Comment by lllMohandarlll** [comment]
any news?

**Comment by cosmicdan** [comment]
This is annoying the crap out of me too (I currently maintain a custom fork of Enviromine for the Reign modpack, Enviromine is otherwise "finished" though).

It's definitely a bug in GalaxySpace. As the original issue creator said, once you remove GalaxySpace it no longer happens. It's easily reproducible. There's nothing in EnviroMine I can do to fix this.

I would investigate the issue myself, but your mod isn't opensource. You don't seem to have any interest in investigating it either, so I guess we'll just be getting rid of GalaxySpace and using a different GalactiCraft expansion. Thanks anyway.

Making this comment in case there's an update on this issue one day.

**Comment by Dulciphi** [comment]
In order to reproduce this, load an instance with Galacticraft and Enviromine. Enviromine physics is enabled by default. No configuration is required. 

1. Start a new world. Spawn in the overworld
2. Go up to any standard Minecraft tree (or simply stack any 5 log blocks vertically). 
3. Break the log at the bottom of the tree or log stack. 
4. Observe that all of the blocks above "fall" down a blockspace. There are no log blocks floating in the air.

Exit, then add Galaxy Space. Restart the minecraft instance and repeat steps 1-3 from above. 
Observe that only the log block that was second from the bottom falls. To say it another way, only the block directly above the block that is removed will respond to gravity. The blocks above it do not. They are floating in air.

This may be an issue with block updates but I am not a skilled coder so I can only describe the problem.

The issue described here also occurs with the Extra Planets addon, but it does not occur with standalone Galacticraft and Enviromine. I hope this description can help.

**Comment by cosmicdan** [comment]
Small update:

This bug also exists in Extra Planets. So either Extra Planets has "borrowed" the same buggy code/technique from GalaxySpace *or* it's a problem at GalactiCraft's end, in their API or whatever. I could present the issue to the official mod, but again as I can't see your source I'm not certain of where the issue actually is.

My guess is that something is consuming a block update event when it shouldn't be, be it by not calling super, setting an event as cancelled, or returning the wrong boolean flag - something like that.

**Comment by lightning02** [comment]
@BlesseNtumble  it's not that hard to reproduce..
install forge 10.13.4.1614
add galacticraft (even latest version)
-GalacticraftCore-1.7-3.0.12.501
-Galacticraft-Planets-1.7-3.0.12.501
-MicdoodleCore-1.7-3.0.12.501
+ GalaxySpace-1.1.4 STABLE
and 
-EnviroMine-1.3.124
in the mod folder.

Create a new world and wait about 50-60 seconds, so the Enviromine physic kicks in.
Try to cut a tree in survival or in creative mode (doesn't make difference).

You will noticed  that only one piece of log will fall instead of the whole tree.

Normally, all the logs that compose a tree should fall down in the moment where you break one piece of the tree.

**Comment by BlesseNtumble** [comment]
I started the MC without GalaxySpace - the result: also several logs fall, but not completely the tree.
So the error is not in the addon.

**Comment by lightning02** [comment]
http://i.imgur.com/zkUhZPK.png

http://i.imgur.com/3rsjPkv.png

@BlesseNtumble
This is the normal behavior of enviromine (galacticraft does not affect it).
As you see every log falls, and when the highest log is not in contact with leaves anymore the leaves, usually, but not always, get destroyed too.
This is what I meant with "the tree falls".
When you have galaxy space installaed the log 1, 2 and 3 that you see in the last screenshot don't fall at all.

**Comment by lightning02** [comment]
Anyway if you are curious, the total-tree-falling usually also occurs in trees that are alone and not in contact with other trees/leaves.
Like this one;
http://i.imgur.com/Os3bsvE.png
it could take a bit before the game realize that it has to destroy all the remaining leaves at once.
By the way this is enviromine business.
The problem is that when you add the galacticraft addon enviromine start to behave differently, letting fall only 1 log each time you break the one underneath, instead of allowing all the logs to fall down.
