### ISSUE TITLE
Проблема с памятью  reopened 

### ISSUE THREAD

**Issue by KiraLinux** [BlesseNtumble/GalaxySpace#145]
не выгружается неиспользуемые данные в игре и забивает выделенную память когда я нахожусь на планетах
что естественно начинаются дики лаги 
хоть пять, хоть семь памяти выделю, все равно забивает и давится потом

[2017-03-14_032410.zip](https://github.com/BlesseNtumble/GalaxySpace/files/839946/2017-03-14_032410.zip)
[logs.zip](https://github.com/BlesseNtumble/GalaxySpace/files/839948/logs.zip)

если мало информации ,то я могу записать на видео происходящее

**Comment by BlesseNtumble** [comment]
Это баг GalactiCraft3

**Comment by KiraLinux** [comment]
Вы можете им написать о данной проблеме?
а то мой ущербный английский, не хочу позориться

**Comment by KiraLinux** [comment]
мне сказали сюда обратится с данной проблемой памяти 

https://github.com/micdoodle8/Galacticraft/issues/2455

**Comment by radfast** [comment]
@BlesseNtumble I asked KiraLinux to come back here because I think if you guys talk to each other in Russian, you have a better chance of helping each other.

I do not see that GC3 can be causing a memory problem as described.  **Dimensions** use a small amount of memory and server tick time.  Loaded **chunks** use memory and tick time, but I think there will be no loaded chunks in these planet dimensions ... or maybe a small number like 1 or 2 chunks only for each planet.

Please can you investigate further.  If you find that GC3 (and not another mod) is causing a memory problem, please re-open micdoodle8/Galacticraft#2455 but it will help me to have clear information about the exact cause of the problem and what testing has been done to show it is Galacticraft.

**Comment by BlesseNtumble** [comment]
Это на сервере?

**Comment by KiraLinux** [comment]
На сервере и в клиенте

**Comment by KiraLinux** [comment]
Хочется все же спросить, почему так долго?
