### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by KenyMylankca** [BlesseNtumble/GalaxySpace#408]
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.244
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.12
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.13
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
OPEN TO LAN
------------------------------------------------------------------------
Description of the issue:
it says a fatal error occured when trying to join a local world (open to LAN)

**Comment by BlesseNtumble** [comment]
Caused by: java.lang.NullPointerException
    at com.animania.network.client.CapSyncPacketHandler$1.run(CapSyncPacketHandler.java:25)

**Comment by KenyMylankca** [comment]
but it doesn't happen with galaxy space 2.0.11

**Comment by BlesseNtumble** [comment]
redownload build and try

**Comment by KenyMylankca** [comment]
i downloaded it 15 mins ago.

**Comment by KenyMylankca** [comment]
Hey uhm, it happens without animania too. i tried with galacticraft + galaxy space only, u cant join to LAN world. please fix it. thanks.

**Comment by KenyMylankca** [comment]
u can try it too. u can't join to local world (open to lan) with galacticraft.244 + galaxyspace

**Comment by KenyMylankca** [comment]
@BlesseNtumble 
With:
GalacticraftCore-1.12.2-4.0.2.244
Galacticraft-Planets-1.12.2-4.0.2.244
MicdoodleCore-1.12.2-4.0.2.244

GalaxySpace-1.12.2-2.0.12
AsmodeusCore-1.12.2-0.0.13

u can't join a local world. hope u fix it. thanks.

**Comment by BlesseNtumble** [comment]
give log without animania

**Comment by KenyMylankca** [comment]
[debug.log](https://github.com/BlesseNtumble/GalaxySpace/files/4416454/debug.log)
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/4416456/latest.log)

**Comment by KenyMylankca** [comment]
@BlesseNtumble i'm still here for any troubleshooting.

**Comment by rualss** [comment]
Same problem

**Comment by P0kerFace228** [comment]
Strange, when trying to play multiplayer, namely when connecting writes: "Fatal error". This is not available in early versions. And the error is only for those who connect. For example, if you start a local host, the one who connects will crash, and if you start the server as a client, it will start, but those who connect to this server will immediately crash with the same error, even if this server is on your PC. Again, there is no such thing on previous versions. There are no conflicting mods and there was no problem with the new version. The log window is not shown, because there is no crash, there is only an internal network error....
![xfiiSOW-tlg](https://user-images.githubusercontent.com/63017575/78179910-a7df3500-746a-11ea-9063-aa91e0a82b3c.jpg)

**Comment by Stiller90** [comment]
I got the same issue too, im using the previous version for the time being

**Comment by KenyMylankca** [comment]
@BlesseNtumble i tried the latest build u uploaded about this crash, and i can't even create a new world. can you? it gives the same error while trying to create new world. then it returns to the multiplayer screen. i think u mixed singleplayer and multiplayer worlds in code.
[debug.log](https://github.com/BlesseNtumble/GalaxySpace/files/4419809/debug.log)
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/4419811/latest.log)

**Comment by KenyMylankca** [comment]
it's fixed on my side in the latest build.
