### ISSUE TITLE
Вылет при создании мира!

### ISSUE THREAD

**Issue by KiraLinux** [BlesseNtumble/GalaxySpace#77]
[crash-2016-07-25_15.08.04-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/381437/crash-2016-07-25_15.08.04-server.txt)

Ошибка не постоянная

**Comment by MeSoLost** [comment]
You have 4-Space installed which would conflict with GalaxySpace since they both attempt to add the same planets.  (had this conflict with another mod)

```
UCHIJAAAA   SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
UCHIJAAAA   SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
UCHIJAAAA   SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
UCHIJAAAA   SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
UCHIJAAAA   SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
UCHIJAAAA   SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
```

THERE it is, GalacticraftPlanets directly conflicts with GalaxySpace.  This is the problem i had.

```
UCHIJAAAA   GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.462.jar) 
UCHIJAAAA   GalaxySpace{1.1.0} [GalaxySpace] (GalaxySpace-1.1.0 STABLE.jar) 
```

Try removing the duplicate planets.
(mod author: sorry to but in but I've had this issue so I thought I'd help ya out a bit.)

**Comment by MeSoLost** [comment]
I was wrong about GalacticraftPlanets. Leave that there -.-  It was something else that gave me my error.
