### ISSUE TITLE
Assembly machine eating materials

### ISSUE THREAD

**Issue by MeSoLost** [BlesseNtumble/GalaxySpace#89]
When using any item transport to attempt to automate assembly IC2 copper ingots the system fails with consequences.  I can hand place the ingots in the machine with no issue.
AE- ic2 copper simply vanish (not in machine, not stored in ME interface, no longer on ME network) tin places in ok but only into slot 2
Thermal Dynamics - servo wont push out of chest to feed, retriever doesnt see machine as a valid destination
BC - works but only for slot 2 and only first item, every item that follow just vanishes

This bug is easily repeatable.  Let me know if you need any other info or pics/vid of my setup or anything else.

edit: running on KCauldron 1.7.10 r0.1

**Comment by MeSoLost** [comment]
Meant aluminum, not tin.  Tried alternate ME Interface block and same issue BUT the copper made it in and not the aluminum. It appears as though only the 2nd slot can have items placed in it by item transport.

**Comment by MeSoLost** [comment]
upgraded to thermos and now when i try and put items into the assembly machine via thermal dynamics the server gets stuck in a crash loop -.- glad i have hourly backups so i didnt loose much

**Comment by MeSoLost** [comment]
if anyone else is having this problem let me know and i'll drop in the CommandHelper script I wrote to prevent item transport from being used with this device until it can be repaired. (would require you to get the item id's of your pipes to put in the pipe id array but that's all(can't find support for forge universal name system for commandhelper -.-))

**Comment by MeSoLost** [comment]
ok got a little help on getting forge id data from within commandhelper so i may have a universal script soon. still working on it

**Comment by MordinSolus** [comment]
I have the same/similar problem. I tried to automate the production of the assembly machine with computercraft and openperipheral, but the assembly machine has only 2 Inventory Slots. There are only one for the Input and not 9. I can automate the production of the electric Compressor from Galacticraft because there is for every InputSlot a unique Slotnumber ( Slotnumber 4 - Slotnumber 12 ) but the assembly machine take items only on Slot 0. After filling one or two items into Slot 0 the rest of the items overwrite the first items or disappear (don't know exactly what happend).

GalaxySpace-1.1.1 STABLE
GalacticraftCore-1.7-3.0.12.462
Galacticraft-Planets-1.7-3.0.12.462

**Comment by BlesseNtumble** [comment]
You can screenshot / diagram or something like that, your buildings?

**Comment by bagomot** [comment]
У нас на сервере тот же баг с этой машиной. Не принимает ни по МЭ-сети, ни по трубам (билдкрафт, термал). Точнее принимает и даже крафтит, но как только открываешь GUI, то сразу крашится сервер. Если же сломать машину, когда в нее что-то поступило, то ничего не выпадает. Если все делать вручную, то нормально. И мы даже не можем запретить ничего, живем от краша до краша. 

Если нужно, проведем все тесты и предоставим логи, пишите мне в вк (@bagomot)
